site_name: TrackStacker Documentation!
nav:
  - Home: 'index.md'
  - 'Tracks!':
    - 'TrackLibrary Home': 'tracks/tracks.md'
    - 'Straight Family': 'tracks/straight.md'
    - '<90 Family': 'tracks/90.md'
    - '<60 Family': 'tracks/60.md'
    - '<45 Family': 'tracks/45.md'
    - '<30 Family': 'tracks/30.md'
    - 'Triad': 'tracks/trd.md'
    - 'Merge/Diverge': 'tracks/md.md'
    - 'Lovejoy': 'tracks/lj.md'
    - 'Inline Buttons': 'tracks/ib.md'
    - '2 to 1': 'tracks/2t1.md'
    - 'Double Button': 'tracks/db.md'
    - 'Inline Valve': 'tracks/ivm.md'
    - 'Chaos Box': 'tracks/cb.md'
  - 'Fabrication!':
    - 'Fabrication Guide': 'fabrication.md'
  - 'Design Guide!':
    - 'Design Guide': 'design.md'
  - 'Changelog':
    - 'Changelog': 'changelog.md'


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  logo: img/LOGOS/base_profile_red.png
  font:
    text: Overpass
  language: en
  palette:
    - scheme: dark
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime
      


extra:
  homepage: https://trackstacker.net
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xH38mFrtfa
    - icon: fontawesome/brands/github-alt
      link: https://github.com/shaurjyabanerjee/TRACKSTACKER
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/trackstacker_toys/?utm_source=ig_web_button_share_sheet
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@trackstacker?_t=8n8mwZbu79b&_r=1

copyright: |
  &copy; 2024 <a href="https://www.trackstacker.net/build"  target="_blank" rel="noopener">TrackStacker.net</a>
